export { setupFTS5, migrateExistingToFTS, populateContentText } from './fts5';
export { setupResources } from './006_resources';
export { upgradeConnections } from './007_connections_v2';
export { setupResourcesFTS, migrateExistingResourcesToFTS } from './resources_fts';
export { addResourceEmbeddingsSupport } from './embeddings_resources';
export { setupMergeCandidates } from './008_merge_candidates';
export { setupResourceStructure } from './009_resource_structure';
export { setupPreferenceSignals } from './010_preference_signals';
export { setupKnowledgeSchemas } from './011_knowledge_schemas';
export { setupBackgroundJobs } from './012_background_jobs';
